version: '3'
services:
  web:
    build: .
    ports:
        - "80:80"
        - "443:443"
    environment:       
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - ASPNETCORE_Kestrel__Certificates__Default__Password=mypassword123
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
        - solr
    volumes: 
        - ..\https:/https/
  solr:
    image: solr:8
    ports:
     - "8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - taxsaleinfo
volumes:
  data: