version: '3'
services:
  web:
    build: .
    ports:
        - "8000:80"
    depends_on:
        - solr
  solr:
    image: solr:8
    ports:
     - "8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - gettingstarted
volumes:
  data: